# Generated by Django 6.0.7 on 2026-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(default='', max_length=2123),
            preserve_default=False,
        ),
    ]
